export const LOAD_IMAGES_LIST = 'LOAD_IMAGES_LIST';
export const LOAD_IMAGES_LIST_SUCCESS = 'LOAD_IMAGES_LIST_SUCCESS';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const LOAD_IMAGE = 'LOAD_IMAGE';
export const LOAD_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS';
